# Generated by Django 4.0 on 2021-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_id',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
