# Generated by Django 4.0 on 2021-12-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitem_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='product_id',
        ),
    ]
