# Generated by Django 4.0 on 2022-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productitem_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_quantity',
            field=models.CharField(max_length=200),
        ),
    ]
